# Generated by Django 4.0.5 on 2022-06-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biography', models.TextField(max_length=2000)),
                ('birth_date', models.DateField()),
                ('country', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='artists')),
            ],
        ),
    ]
