# Generated by Django 4.0.5 on 2022-06-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_museum', '0002_meduim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meduim',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
