# Generated by Django 4.0.5 on 2022-06-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_museum', '0004_alter_meduim_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('city', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='museums')),
            ],
        ),
    ]
