# Generated by Django 4.0.5 on 2022-06-23 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_museum', '0005_museum'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(null=True, upload_to='museums')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_museum.artist')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_museum.meduim')),
                ('museum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_museum.museum')),
            ],
        ),
    ]
